services:
  - type: web
    name: whisper-api
    env: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      apt-get update
      apt-get install -y ffmpeg
    startCommand: uvicorn Hosted_WS_APP:app --host 0.0.0.0 --port $PORT